apiVersion: 1
groups:
    - orgId: 1
      name: 1 minute
      folder: Proxmox Alerts
      interval: 1m
      rules:
        - uid: aeka4dp79ai9sb
          title: Storage Pools
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 3600
                to: 0
              datasourceUid: bejsypfy2b3eoa
              model:
                datasource:
                    type: influxdb
                    uid: bejsypfy2b3eoa
                intervalMs: 1000
                maxDataPoints: 43200
                query: |
                    import "math"
                    from(bucket: "proxmox")
                      |> range(start: v.timeRangeStart, stop:v.timeRangeStop)
                      |> filter(fn: (r) => r._measurement == "system")
                      |> filter(fn: (r) => r._field == "avail")
                      |> map(fn: (r) => ({r with _value: float(v: r._value) / 1073741824.0}))
                      |> last()
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 30
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: IfgdXjtnk
          panelId: 14
          noDataState: OK
          execErrState: Error
          annotations:
            __dashboardUid__: IfgdXjtnk
            __panelId__: "14"
            summary: Storage pool "{{ $labels.host }}" ({{$labels.type}}) on node {{ $labels.nodename }} has {{ $values.B.Value | printf "%.1f" }} GB remaining
          isPaused: false
          for: 0s
          notification_settings:
            receiver: ZPH Discord
