[agent]
    omit_hostname = true
    interval = "30s"
    flush_interval = "45s"

[[inputs.mqtt_consumer]]
    servers = ["tcp://mosquitto:1883"]
    username = "$TELEGRAF_MQTT_USERNAME"
    password = "$TELEGRAF_MQTT_PASSWORD"
    topics = [ "plug/+/status/switch:0" ]
    topic_tag = ""
    data_format = "json_v2"
    name_override = "plugs"

    [[inputs.mqtt_consumer.topic_parsing]]
        topic = "plug/+/status/switch:0"
        tags = "_/plug_id/_/_"

    [[inputs.mqtt_consumer.json_v2]]
        timestamp_path = "aenergy.minute_ts"
        timestamp_format = "unix"

        [[inputs.mqtt_consumer.json_v2.field]]
        path = "current"
        type = "float"

        [[inputs.mqtt_consumer.json_v2.field]]
        path = "voltage"
        type = "float"

        [[inputs.mqtt_consumer.json_v2.field]]
        path = "apower"
        rename = "wattage"
        type = "float"

        [[inputs.mqtt_consumer.json_v2.field]]
        path = "temperature.tC"
        rename = "temperature"
        type = "float"

        [[inputs.mqtt_consumer.json_v2.field]]
        path = "output"
        rename = "switched_on"
        type = "bool"

        [[inputs.mqtt_consumer.json_v2.field]]
        path = "aenergy.total"
        rename = "consumed"
        type = "float"

[[inputs.mqtt_consumer]]
    servers = ["tcp://mosquitto:1883"]
    username = "$TELEGRAF_MQTT_USERNAME"
    password = "$TELEGRAF_MQTT_PASSWORD"
    topics = ["distro/+/status/em1:0", "distro/+/status/em1:1", "distro/+/status/em1:2"]
    topic_tag = ""
    data_format = "json_v2"
    name_override = "distros"

    [[inputs.mqtt_consumer.topic_parsing]]
        topic = "distro/+/status/+"
        tags = "_/distro_id/_/phase"

    [[inputs.mqtt_consumer.json_v2]]

        [[inputs.mqtt_consumer.json_v2.field]]
        path = "voltage"
        rename = "volts"
        type = "float"

        [[inputs.mqtt_consumer.json_v2.field]]
        path = "current"
        rename = "amps"
        type = "float"

        [[inputs.mqtt_consumer.json_v2.field]]
        path = "act_power"
        rename = "watts"
        type = "float"

        [[inputs.mqtt_consumer.json_v2.field]]
        path = "aprt_power"
        rename = "volt_amps"
        type = "float"

        [[inputs.mqtt_consumer.json_v2.field]]
        path = "pf"
        rename = "power_factor"
        type = "float"

        [[inputs.mqtt_consumer.json_v2.field]]
        path = "freq"
        rename = "frequency"
        type = "float"

[[inputs.mqtt_consumer]]
    servers = ["tcp://mosquitto:1883"]
    username = "$TELEGRAF_MQTT_USERNAME"
    password = "$TELEGRAF_MQTT_PASSWORD"
    topics = [
        "distro/+/status/em1data:0", 
        "distro/+/status/em1data:1", 
        "distro/+/status/em1data:2"
    ]
    topic_tag = ""
    data_format = "json_v2"
    
    name_override = "distros"

    [[inputs.mqtt_consumer.topic_parsing]]
        topic = "distro/+/status/+"
        tags = "_/distro_id/_/phase"

    [[inputs.mqtt_consumer.json_v2]]

        [[inputs.mqtt_consumer.json_v2.field]]
        path = "total_act_energy"
        rename = "consumed"
        type = "float"

        [[inputs.mqtt_consumer.json_v2.field]]
        path = "total_act_ret_energy"
        rename = "returned"
        type = "float"

[[processors.enum]]
  namepass = ["distros"]

  [[processors.enum.mapping]]
    tag = "phase"
    dest = "phase"
    
    [processors.enum.mapping.value_mappings]
      "em1:0" = "1"
      "em1:1" = "2"
      "em1:2" = "3"
      "em1data:0" = "1"
      "em1data:1" = "2"
      "em1data:2" = "3"

[[outputs.influxdb_v2]]
    urls = ["http://influxdb:8086"]
    token = "$DOCKER_INFLUXDB_INIT_ADMIN_TOKEN"
    organization = "$DOCKER_INFLUXDB_INIT_ORG"
    bucket = "power"
