apiVersion: 1

datasources:
  - name: InfluxDB
    uid: bejsypfy2b3eoa
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: zph
      defaultBucket: plugs
    secureJsonData:
      token: $INFLUXDB_TOKEN
